// ObsSessions

export const GET_OBSSESSIONS_BEGIN = "GET_OBSSESSIONS_BEGIN";
export type GET_OBSSESSIONS_BEGIN = typeof GET_OBSSESSIONS_BEGIN;

export const GET_OBSSESSIONS_SUCCESS = "GET_OBSSESSIONS_SUCCESS";
export type GET_OBSSESSIONS_SUCCESS = typeof GET_OBSSESSIONS_SUCCESS;

export const GET_OBSSESSIONS_FAILURE = "GET_OBSSESSIONS_FAILURE";
export type GET_OBSSESSIONS_FAILURE = typeof GET_OBSSESSIONS_FAILURE;

// --

export const SELECT_OBSSESSION = "SELECT_OBSSESSION";
export type SELECT_OBSSESSION = typeof SELECT_OBSSESSION;

export const NEW_OBSSESSION = "NEW_OBSSESSION";
export type NEW_OBSSESSION = typeof NEW_OBSSESSION;

// --

export const MODIFYING_OBSSESSION_BEGIN = "MODIFYING_OBSSESSION_BEGIN";
export type MODIFYING_OBSSESSION_BEGIN = typeof MODIFYING_OBSSESSION_BEGIN;

export const ADD_OBSSESSION_SUCCESS = "ADD_OBSSESSION_SUCCESS";
export type ADD_OBSSESSION_SUCCESS = typeof ADD_OBSSESSION_SUCCESS;

export const UPDATE_OBSSESSION_SUCCESS = "UPDATE_OBSSESSION_SUCCESS";
export type UPDATE_OBSSESSION_SUCCESS = typeof UPDATE_OBSSESSION_SUCCESS;

export const DELETE_OBSSESSION_SUCCESS = "DELETE_OBSSESSION_SUCCESS";
export type DELETE_OBSSESSION_SUCCESS = typeof DELETE_OBSSESSION_SUCCESS;

export const MODIFYING_OBSSESSION_FAILURE = "MODIFYING_OBSSESSION_FAILURE";
export type MODIFYING_OBSSESSION_FAILURE = typeof MODIFYING_OBSSESSION_FAILURE;

// Locations

export const GET_LOCATIONS_BEGIN = "GET_LOCATIONS_BEGIN";
export type GET_LOCATIONS_BEGIN = typeof GET_LOCATIONS_BEGIN;

export const GET_LOCATIONS_SUCCESS = "GET_LOCATIONS_SUCCESS";
export type GET_LOCATIONS_SUCCESS = typeof GET_LOCATIONS_SUCCESS;

export const GET_LOCATIONS_FAILURE = "GET_LOCATIONS_FAILURE";
export type GET_LOCATIONS_FAILURE = typeof GET_LOCATIONS_FAILURE;
