// Authentication

export const LOGGED_IN = "LOGGED_IN";
export type LOGGED_IN = typeof LOGGED_IN;

export const LOGGED_OUT = "LOGGED_OUT";
export type LOGGED_OUT = typeof LOGGED_OUT;

// ObsSessions

export const GET_OBSSESSIONS_BEGIN = "GET_OBSSESSIONS_BEGIN";
export type GET_OBSSESSIONS_BEGIN = typeof GET_OBSSESSIONS_BEGIN;

export const GET_OBSSESSIONS_SUCCESS = "GET_OBSSESSIONS_SUCCESS";
export type GET_OBSSESSIONS_SUCCESS = typeof GET_OBSSESSIONS_SUCCESS;

export const GET_OBSSESSIONS_FAILURE = "GET_OBSSESSIONS_FAILURE";
export type GET_OBSSESSIONS_FAILURE = typeof GET_OBSSESSIONS_FAILURE;

// --

export const SELECT_OBSSESSION = "SELECT_OBSSESSION";
export type SELECT_OBSSESSION = typeof SELECT_OBSSESSION;

export const NEW_OBSSESSION = "NEW_OBSSESSION";
export type NEW_OBSSESSION = typeof NEW_OBSSESSION;

// --

export const MODIFYING_OBSSESSION_BEGIN = "MODIFYING_OBSSESSION_BEGIN";
export type MODIFYING_OBSSESSION_BEGIN = typeof MODIFYING_OBSSESSION_BEGIN;

export const ADD_OBSSESSION_SUCCESS = "ADD_OBSSESSION_SUCCESS";
export type ADD_OBSSESSION_SUCCESS = typeof ADD_OBSSESSION_SUCCESS;

export const UPDATE_OBSSESSION_SUCCESS = "UPDATE_OBSSESSION_SUCCESS";
export type UPDATE_OBSSESSION_SUCCESS = typeof UPDATE_OBSSESSION_SUCCESS;

export const DELETE_OBSSESSION_SUCCESS = "DELETE_OBSSESSION_SUCCESS";
export type DELETE_OBSSESSION_SUCCESS = typeof DELETE_OBSSESSION_SUCCESS;

export const MODIFYING_OBSSESSION_FAILURE = "MODIFYING_OBSSESSION_FAILURE";
export type MODIFYING_OBSSESSION_FAILURE = typeof MODIFYING_OBSSESSION_FAILURE;

// Locations

export const GET_LOCATIONS_BEGIN = "GET_LOCATIONS_BEGIN";
export type GET_LOCATIONS_BEGIN = typeof GET_LOCATIONS_BEGIN;

export const GET_LOCATIONS_SUCCESS = "GET_LOCATIONS_SUCCESS";
export type GET_LOCATIONS_SUCCESS = typeof GET_LOCATIONS_SUCCESS;

export const GET_LOCATIONS_FAILURE = "GET_LOCATIONS_FAILURE";
export type GET_LOCATIONS_FAILURE = typeof GET_LOCATIONS_FAILURE;

// Search

export const SEARCH = "SEARCH";
export type SEARCH = typeof SEARCH;

export const CLEAR_SEARCH = "CLEAR_SEARCH";
export type CLEAR_SEARCH = typeof CLEAR_SEARCH;

// Comparing images/sketches

export const RESOURCE_CHECKED = "RESOURCE_CHECKED";
export type RESOURCE_CHECKED = typeof RESOURCE_CHECKED;

export const RESOURCE_UNCHECKED = "RESOURCE_UNCHECKED";
export type RESOURCE_UNCHECKED = typeof RESOURCE_UNCHECKED;

export const RESOURCE_ALL_CLEARED = "RESOURCE_ALL_CLEARED";
export type RESOURCE_ALL_CLEARED = typeof RESOURCE_ALL_CLEARED;
