rmdir /s /q ..\ObsToolApi\ObsTool\bin
rmdir /s /q ..\ObsToolApi\ObsTool\obj
rmdir /s /q ..\ObsToolApi\ObsTool.Test\bin
rmdir /s /q ..\ObsToolApi\ObsTool.Test\obj
rmdir /s /q ..\ObsToolClient\node_modules
rmdir /s /q ..\ObsToolClient\dist
rmdir /s /q ..\ObsToolClient\build
rmdir /s /q ..\ObsToolWebserver\node_modules
rmdir /s /q ..\ObsToolWebserver\dist
rmdir /s /q ..\ObsToolWebserver\build
